# Generated by Django 3.1 on 2022-09-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('send', models.BooleanField(default=False)),
                ('broadcast_on', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'BroadcastNotification',
                'verbose_name_plural': 'BroadcastNotifications',
                'ordering': ['-broadcast_on'],
            },
        ),
    ]
